# Generated by Django 5.2.11 on 2026-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profilephoto',
            field=models.ImageField(upload_to='media'),
        ),
    ]
