# Generated by Django 5.2.11 on 2026-03-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_register_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profilephoto',
            field=models.FileField(upload_to='profile'),
        ),
    ]
