# Generated by Django 5.2.11 on 2026-03-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='deliverydate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='orderdate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='orderstatus',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='paymentstatus',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tracking_id',
            new_name='trackingid',
        ),
    ]
