# Generated by Django 5.2.11 on 2026-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
