# Generated by Django 5.2.11 on 2026-04-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
