# Generated by Django 5.2.11 on 2026-04-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
